name: Build and Push MeffleOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Buildah
        uses: redhat-actions/setup-buildah@v1.5.0

      - name: Build container
        uses: redhat-actions/buildah-build@v2.10.0
        with:
          image: meffleos
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: mefflecakes/meffleos
          tags: latest
