name: Build and Push Custom Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed for pushing to GHCR
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up container build environment
        uses: containers/podman-install@v1

      - name: Build image
        run: |
          podman build -t localhost/meffleos .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image
        run: |
          podman tag localhost/meffleos ghcr.io/${{ github.repository_owner }}/meffleos:latest

      - name: Push image to GHCR
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/meffleos:latest
